### ISSUE TITLE
🔨 🎨 Refactor Email Template with Updating HTML Design

### ISSUE THREAD

**Issue by FATEMEH-Z-HASHEMI** [Lazarus-org/django_logging#85]
## Description 
I plan to refactor the email template used in the `django_logging` package by redesigning the HTML structure with a fresh style. This update aims to improve the appearance and make the template more modern and visually appealing.

## To-do
- Redesign the HTML layout of the email template.
- Implement a new style that enhances readability and aesthetics.
- Test the new email template to ensure proper rendering across different email clients.

## Notes
I will take on the task of designing and implementing this updated email template.

**Comment by MEHRSHAD-MIRSHEKARY** [comment]
Ok, can you create pull request and share your updated template?

**Comment by FATEMEH-Z-HASHEMI** [comment]
> Ok, can you create pull request and share your updated template?

of course!

**Comment by ARYAN-NIKNEZHAD** [comment]
@FATEMEH-Z-HASHEMI 
Thank you for bringing this issue to our attention. Please feel free to submit a pull request whenever you're ready, and we'd be happy to review it!
